//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIPROJECT._0000
{
    using System;
    using System.Collections.Generic;
    
    public partial class Историязаказов
    {
        public int IDистории1 { get; set; }
        public Nullable<int> Фамилия2 { get; set; }
        public Nullable<int> Имя2 { get; set; }
        public Nullable<int> Отчество2 { get; set; }
        public Nullable<int> Поставщик2 { get; set; }
        public Nullable<int> Банк2 { get; set; }
        public Nullable<int> Сумма2 { get; set; }
        public Nullable<int> ДатаЗаказа2 { get; set; }
        public string Статус { get; set; }
        public Nullable<System.DateTime> ОкончательнаяДата { get; set; }
    
        public virtual Заказы Заказы { get; set; }
        public virtual Заказы Заказы1 { get; set; }
        public virtual Заказы Заказы2 { get; set; }
        public virtual Заказы Заказы3 { get; set; }
        public virtual Заказы Заказы4 { get; set; }
        public virtual Клиенты Клиенты { get; set; }
        public virtual Клиенты Клиенты1 { get; set; }
        public virtual Клиенты Клиенты2 { get; set; }
        public virtual Платежи Платежи { get; set; }
        public virtual Поставщики Поставщики { get; set; }
        public virtual Поставщики Поставщики1 { get; set; }
    }
}
